/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as GoalsIndexRouteImport } from './routes/goals/index'
import { Route as GoalsGoalIdRouteImport } from './routes/goals/$goalId'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as TodayIndexRouteImport } from './routes/today/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GoalsRoute,
} as any)
const GoalsGoalIdRoute = GoalsGoalIdRouteImport.update({
  id: '/$goalId',
  path: '/$goalId',
  getParentRoute: () => GoalsRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayIndexRoute = TodayIndexRouteImport.update({
  id: '/today/',
  path: '/today/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goals': typeof GoalsRouteWithChildren
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/goals/': typeof GoalsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/today/': typeof TodayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/goals': typeof GoalsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/today': typeof TodayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/goals': typeof GoalsRouteWithChildren
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/goals/': typeof GoalsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/today/': typeof TodayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/goals'
    | '/goals/$goalId'
    | '/goals/'
    | '/reports/'
    | '/settings/'
    | '/today/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/goals/$goalId' | '/goals' | '/reports' | '/settings' | '/today'
  id:
    | '__root__'
    | '/'
    | '/goals'
    | '/goals/$goalId'
    | '/goals/'
    | '/reports/'
    | '/settings/'
    | '/today/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoalsRoute: typeof GoalsRouteWithChildren
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TodayIndexRoute: typeof TodayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/': {
      id: '/goals/'
      path: '/'
      fullPath: '/goals/'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof GoalsRoute
    }
    '/goals/$goalId': {
      id: '/goals/$goalId'
      path: '/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof GoalsGoalIdRouteImport
      parentRoute: typeof GoalsRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today/': {
      id: '/today/'
      path: '/today'
      fullPath: '/today/'
      preLoaderRoute: typeof TodayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GoalsRouteChildren {
  GoalsGoalIdRoute: typeof GoalsGoalIdRoute
  GoalsIndexRoute: typeof GoalsIndexRoute
}

const GoalsRouteChildren: GoalsRouteChildren = {
  GoalsGoalIdRoute: GoalsGoalIdRoute,
  GoalsIndexRoute: GoalsIndexRoute,
}

const GoalsRouteWithChildren = GoalsRoute._addFileChildren(GoalsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoalsRoute: GoalsRouteWithChildren,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TodayIndexRoute: TodayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
